### ISSUE TITLE
language file needs update

### ISSUE THREAD

**Issue by UUdC** [cubicoder/tutorialmod#1]
In the tutorial the identifying name for the axe is "tutorial_axe". In the current language file this is "axeTutorial".

```
item.tutorialmod.tutorial_axe.name=Tutorial Axe
item.tutorialmod.tutorial_pickaxe.name=Tutorial Pickaxe
item.tutorialmod.tutorial_hoe.name=Tutorial Hoe
item.tutorialmod.tutorial_shovel.name=Tutorial Shovel
item.tutorialmod.tutorial_sword.name=Tutorial Sword

item.tutorialmod.tutorial_helmet.name=Tutorial Helmet
item.tutorialmod.tutorial_chestplate.name=Tutorial Chestplate
item.tutorialmod.tutorial_leggings.name=Tutorial Leggings
item.tutorialmod.tutorial_boots.name=Tutorial Boots
```

**Comment by Cadiboo** [comment]
> In the tutorial the identifying name for the axe is "tutorial_axe". In the current language file this is "axeTutorial".

As you can see in https://github.com/cubicoder/tutorialmod/blob/9d13a4838702f30d84836d5cac85ab0b73af79ad/src/main/java/com/cubicoder/tutorial/util/RegistryHandler.java#L39 and https://github.com/cubicoder/tutorialmod/blob/8d90cb20318fb5f5bc9054def812b185baeba43e/src/main/java/com/cubicoder/tutorial/item/ItemTutorialAxe.java#L12 the unlocalised name (`axeTutorial`) is used instead of the registry name (`tutorial_axe`). As general practice the unlocalised name should be the same as the registry name though.

**Comment by UUdC** [comment]
Ah, I see, thank you. It seems registerhandler.java was not handled in the tutorial. I'll make a note about it.
